# Generated by Django 4.2.3 on 2023-07-24 08:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecommerce", "0005_alter_order_zip_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="zip_code",
            field=models.CharField(max_length=10),
        ),
    ]
